# --------------------------------------------
# Marseille Configuration File
# --------------------------------------------

# --------------------------------------------
# Application Configuration
# --------------------------------------------
Application:
  Name: "The K Look"
  Email: "the.k.look2020@gmail.com"
  Version: "v1.0.0"

# --------------------------------------------
# Language Configuration
# --------------------------------------------
Language:
  English:
    Code: "en"
    Title: "English"
    Currency: "$"
  Spanish:
    Code: "es"
    Title: "Spanish"
    Currency: "€"
  French:
    Code: "fr"
    Title: "French"
    Currency: "€"

# --------------------------------------------
# Build Configuration
# --------------------------------------------
Build:
  Templates: "src"
  Media: "media"
  Package: "build"

# --------------------------------------------
# Style Configuration
# --------------------------------------------
Style:
  White: "#F5F8FA"
  Silver: "#DFE4EA"
  Black: "#282828"
  LightGray: "#F1F2F6"
  DarkGray: "#7f8C8D"
  Primary: "#F7CFE1"
  Secondary: "#F5A4CC"

# --------------------------------------------
# Assets Configuration
# --------------------------------------------
Assets:
  Logo: "brand/the k look v2.png"

# --------------------------------------------
# Strings Configuration
# --------------------------------------------
Strings:
  Home:
    en: "Home"
    es: "Inicio"
    fr: "Domicile"
  Contact:
    en: "Contact"
    es: "Contacto"
    fr: "Contact"
  About:
    en: "About"
    es: "Nosotros"
    fr: "Nous"
  ContactUs:
    en: "Contact Us"
    es: "Contáctenos"
    fr: "Nous Contacter"
  AboutUs:
    en: "About Us"
    es: "Acerca de Nosotros"
    fr: "à propos de nous"
  LoremIpsum:
    en: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    es: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    fr: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  Copyright:
    en: "Copyright ©2021 All rights reserved"
    es: "Copyright ©2021 All rights reserved"
    fr: "Copyright ©2021 All rights reserved"
  PrivacyPolicy:
    en: "Privacy Policy"
    es: "Política de Privacidad"
    fr: "Lorem Ipsum"
  TermsOfService:
    en: "Terms of Service"
    es: "Términos y Condiciones"
    fr: "Lorem Ipsum"
  Description:
    en: "Lorem Ipsum"
    es: "Lorem Ipsum"
    fr: "Lorem Ipsum"
  Keywords:
    en: "Lorem Ipsum"
    es: "Lorem Ipsum"
    fr: "Lorem Ipsum"
  Lifestyle:
    en: "Lifestyle"
    es: "Estilo de Vida"
    fr: "Style de Vie"
  Music:
    en: "Music"
    es: "Música"
    fr: "Musique"
  Food:
    en: "Food"
    es: "Comida"
    fr: "Nourriture"
  Life:
    en: "The K Life"
    es: "The K Life"
    fr: "The K Life"
  Language:
    en: "Language"
    es: "Lenguaje"
    fr: "Lorem Ipsum"
  Coats:
    en: "Coats"
    es: "Sacos"
    fr: "Manteaux"
  Blazers:
    en: "Blazers"
    es: "Americanas"
    fr: "Blazers"
  Accessories:
    en: "Accessories"
    es: "Accesorios"
    fr: "Accessoires"
  SeeMore:
    en: "See more"
    es: "Ver Más"
    fr: "Lorem Ipsum"
  All:
    en: "View All"
    es: "Ver Todo"
    fr: "Voir tout"
  JacketsPuffers:
    en: "Jackets / Puffers"
    es: "Chaquetas / Fumadoras"
    fr: "Veste / Puffers"
  Jackets:
    en: "Jackets"
    es: "Chaquetas"
    fr: "Vestes"
  Puffers:
    en: "Puffers"
    es: "Fumadoras"
    fr: "Puffers"
  Denim:
    en: "Denim"
    es: "Denim"
    fr: "Denim"
  DressesMono:
    en: "Dresses / Monos"
    es: "Vestidos / Monos"
    fr: "Robes / Combinaison"
  Maxi:
    en: "Maxi"
    es: "Maxi"
    fr: "Maxi"
  JumpSuits:
    en: "Jump Suits"
    es: "Mono"
    fr: "Combinaison"
  ShirtsTops:
    en: "Shirts / Tops"
    es: "Camisas / Tops"
    fr: "Chemise / Haunts"
  Shirts:
    en: "Shirts"
    es: "Camisas"
    fr: "Chemises"
  Blouses:
    en: "Blouses"
    es: "Blusas"
    fr: "Chemisières"
  Tops:
    en: "Tops"
    es: "Tops"
    fr: "Tops"
  CropTops:
    en: "Crop Tops"
    es: "Crop Tops"
    fr: "Hauts Courts"
  Tshirts:
    en: "T-Shirts"
    es: "Remeras"
    fr: "T-Shirts"
  Printed:
    en: "Printed"
    es: "Impreso"
    fr: "Imprimée"
  Cropped:
    en: "Cropped"
    es: "Recortado"
    fr: "Tondu"
  LongSleeve:
    en: "Long Sleeve"
    es: "Manga Larga"
    fr: "Manche Longue"
  TankTops:
    en: "Tank Tops"
    es: "Camiseta"
    fr: "Débardeurs"
  ShortSleeve:
    en: "Short Sleeve"
    es: "Manga Corta"
    fr: "Manche Courte"
  Knitwear:
    en: "Knitwear"
    es: "Tricot"
    fr: "Tricots"
  Cardigans:
    en: "Cargidans"
    es: "Cardigán"
    fr: "Cardigans"
  Sweatters:
    en: "Sweaters"
    es: "Suéteres"
    fr: "Chandails"
  KnitTops:
    en: "Knit Tops"
    es: "Tops"
    fr: "Tricots"
  Dresses:
    en: "Dresses"
    es: "Vestidos"
    fr: "Robes"
  TurtleNeck:
    en: "Turtle Neck"
    es: "Cuello de Tortuga"
    fr: "Col Roulé"
  Basics:
    en: "Basics"
    es: "Básicos"
    fr: "Basiques"
  Pants:
    en: "Pants"
    es: "Pantalones"
    fr: "Lorem Ipsum"
  Office:
    en: "Office"
    es: "Oficina"
    fr: "Bureau"
  Legging:
    en: "Leggings"
    es: "Polainas"
    fr: "Leggings"
  Joggers:
    en: "Joggers"
    es: "Corredores"
    fr: "Joggeurs"
  Jeans:
    en: "Jeans"
    es: "Jeans"
    fr: "Jeans"
  HighWaist:
    en: "High Waist"
    es: "Cintura Alta"
    fr: "Taille Haute"
  MidWaist:
    en: "Mid Waist"
    es: "Cintura Media"
    fr: "Taille Moyenne"
  Slouchy:
    en: "Slouchy"
    es: "Desgarbado"
    fr: "Mou"
  MomFit:
    en: "Mom Fit"
    es: "Mom Fit"
    fr: "Maman en Forme"
  Baggy:
    en: "Baggy"
    es: "Holgado"
    fr: "Bouffant"
  Straight:
    en: "Straight"
    es: "Ajustado"
    fr: "Droit"
  Slim:
    en: "Slim"
    es: "Delgado"
    fr: "Mince"
  SkirtsShorts:
    en: "Skirts / Shorts"
    es: "Faldas / Shorts"
    fr: "Jupes / Shorts"
  Mini:
    en: "Mini"
    es: "Mini"
    fr: "Mini"
  Midi:
    en: "Midi"
    es: "Midi"
    fr: "Mi-Longue"
  Pleated:
    en: "Pleated"
    es: "Plisado"
    fr: "Pliseé"
  Shorts:
    en: "Shorts"
    es: "Shorts"
    fr: "Shorts"
  TShirts:
    en: "T-Shirts"
    es: "Remeras"
    fr: "T-Shirts"
  SweatShirt:
    en: "Sweat-Shirt"
    es: "Sudaderas"
    fr: "Sweat-Shirt"
  Bags:
    en: "Bags"
    es: "Bolsos"
    fr: "Sacs"
  CrossBodyBags:
    en: "Cross Body Bags"
    es: "Bolsos Cruzados"
    fr: "SAC BANDOULIÈRES"
  MidiBags:
    en: "Midi Bags"
    es: "Mini Bolso"
    fr: "SAC À MAIN"
  LargeBags:
    en: "Large Bags"
    es: "Bolsa Grande"
    fr: "GRAND SAC / SAC À DOS"
  Jewerly:
    en: "Jewerly"
    es: "Joyería"
    fr: "Bijoux"
  Belts:
    en: "Belts"
    es: "Cinturones"
    fr: "Ceitures"
  Sunglasses:
    en: "Sunglasses"
    es: "Gafas de Sol"
    fr: ""
  HatsCaps:
    en: "Hats / Caps"
    es: "Sombreros / Gorras"
    fr: "Chapeaux"
  Handkerchiefs:
    en: "Handkerchiefs"
    es: "Bufandas"
    fr: "Mouchoir"
  Legal:
    en: "Legal"
    es: "Legal"
    fr: "Legal"
  FastFreeDelivery:
    en: "Fast & Free Delivery"
    es: "Envío Gratis y Rápido"
    fr: "Lorem Ipsum"
  Lorem:
    en: "Lorem Ipsum Dolor Sit Amet"
    es: "Lorem Ipsum Dolor Sit Amet"
    fr: "Lorem Ipsum Dolor Sit Amet"
  FirstCollection:
    en: "Collection Houses Our First-Ever"
    es: "Lorem Ipsum Dolor Sit Amet"
    fr: "Lorem Ipsum Dolor Sit Amet"
  SecondCollection:
    en: "Established fact that by the readable content"
    es: "Lorem Ipsum Dolor Sit Amet"
    fr: "Lorem Ipsum Dolor Sit Amet"
  ThirdCollection:
    en: "Established fact that by the readable content"
    es: "Lorem Ipsum Dolor Sit Amet"
    fr: "Lorem Ipsum Dolor Sit Amet"
  ViewMore:
    en: "View More"
    es: "Ver Mas"
    fr: "Lorem Ipsum"
  SearchPlaceholder:
    en: "What are you looking for?"
    es: "Qué estás buscando?"
    fr: "Lorem Ipsum"
  Search:
    en: "Search"
    es: "Buscar"
    fr: "Lorem Ipsum"
  Catalog:
    en: "Catalog"
    es: "Catálogo"
    fr: "Lorem Ipsum"
  CatalogError:
    en: "The catalog can't be rendered at this moment"
    es: "El catálogo no se puede mostrar en este momento"
    fr: "Lorem Ipsum Dolor Sit Amet"
  Loading:
    en: "Loading..."
    es: "Cargando..."
    fr: "Lorem Ipsum"
  View:
    en: "View"
    es: "Ver"
    fr: "Ipsum"
  Previous:
    en: "Previous"
    es: "Anterior"
    fr: "Ipsum"
  Next:
    en: "Next"
    es: "Siguiente"
    fr: "Ipsum"
  EmptyList:
    en: "Nothing Found Here"
    es: "No Hay Resultados"
    fr: "Lorem Ipsum Dolor Sit Amet..."
  DressesJumpsuits:
    en: "Dresses & Jumpsuits"
    es: "Vestidos"
    fr: "Lorem Ipsum Dolor Sit Amet..."
  JacketsPuffers:
    en: "Jackets & Puffers"
    es: "Chaquetas"
    fr: "Lorem Ipsum Dolor Sit Amet..."
  ShirtsTops:
    en: "Shirts & Tops"
    es: "Remeras y Tops"
    fr: "Lorem Ipsum Dolor Sit Amet..."
  SweatShirt:
    en: "Sweat Shirt"
    es: "Remeras"
    fr: "Lorem Ipsum Dolor Sit Amet..."
  TShirts:
    en: "T-Shirts"
    es: "Camisas"
    fr: "Lorem Ipsum Dolor Sit Amet..."
  Buy:
    en: "Buy Now"
    es: "Comprar Ahora"
    fr: "Lorem Ipsum"
  Color:
    en: "Color"
    es: "Color"
    fr: "Lorem"
  Size:
    en: "Size"
    es: "Tamaño"
    fr: "Ipsum"
  Black:
    en: "Black"
    es: "Negro"
    fr: "Lorem"
  WIP:
    en: "Work In Progress"
    es: "En Construcción"
    fr: "Lorem Ipsum Dolor"
  FindSize:
    en: "Find Your Size"
    es: "Encuentra Tu Talla"
    fr: "Lorem Ipsum Dolor"
  SizeGuide:
    en: "Size Guide"
    es: "Guía De Talla"
    fr: "Lorem Ipsum Dolor"
  AddToCart:
    en: "Add To Cart"
    es: "Agregar Al Carrito"
    fr: "Lorem Ipsum Dolor"
  Checkout:
    en: "Checkout"
    es: "Finalizar Compra"
    fr: "Lorem Ipsum Dolor"
  Subtotal:
    en: "Subtotal"
    es: "Subtotal"
    fr: "Lorem Ipsum Dolor"
  EmptyCart:
    en: "Your Cart is Empty!"
    es: "Tu Carro de Compras está vacío!"
    fr: "Lorem Ipsum Dolor!"
  FindProducts:
    en: "Find Clothes"
    es: "Buscar Prendas"
    fr: "Lorem Ipsum Dolor"
  YourCart:
    en: "Your Cart"
    es: "Carro de Compras"
    fr: "Lorem Ipsum"
  Remove:
    en: "Remove"
    es: "Eliminar"
    fr: "Lorem Ipsum"

# --------------------------------------------
# Slider Configuration 
# --------------------------------------------
Slider:
  FirstCollection:
    Image: "promo/1.jpg"
  SecondCollection:
    Image: "promo/2.jpg"
  ThirdCollection:
    Image: "promo/3.jpg"

# --------------------------------------------
# Links Configuration 
# --------------------------------------------
Link:
  Instagram: "404.html"
  Facebook: "404.html"
  Twitter: "404.html"
  Pinterest: "404.html"
  Music: "404.html"
  Food: "404.html"
  Life: "404.html"
  SizeGuide: "404.html"
  FindSize: "404.html"
