# --------------------------------------------
# Kain Configuration File
# --------------------------------------------

# --------------------------------------------
# Application Configuration
# --------------------------------------------
Application:
  Name: "The K Look"

# --------------------------------------------
# Build Configuration
# --------------------------------------------
Build:
  Templates: "web"
  Package: "build"
