# --------------------------------------------
# Marseille Configuration File
# --------------------------------------------

# --------------------------------------------
# Application Configuration
# --------------------------------------------
Application:
  Name: "The K Look"
  Email: "the.k.look2020@gmail.com"
  Version: "v1.0.0"

# --------------------------------------------
# Language Configuration
# --------------------------------------------
Language:
  English:
    Code: "en"
    Title: "English"
    Currency: "$"
  Spanish:
    Code: "es"
    Title: "Spanish"
    Currency: "€"
  French:
    Code: "fr"
    Title: "French"
    Currency: "€"

# --------------------------------------------
# Build Configuration
# --------------------------------------------
Build:
  Templates: "src"
  Media: "media"
  Package: "build"

# --------------------------------------------
# Style Configuration
# --------------------------------------------
Style:
  White: "#F5F8FA"
  Silver: "#DFE4EA"
  Black: "#282828"
  LightGray: "#F1F2F6"
  DarkGray: "#7f8C8D"
  Primary: "#33d9b2"
  Secondary: "#34ace0"
  Tertiary: "#218c74"

# --------------------------------------------
# Assets Configuration
# --------------------------------------------
Assets:
  Logo: "brand/the k look v2.png"

# --------------------------------------------
# Strings Configuration
# --------------------------------------------
Strings:
  Home:
    en: "Home"
    es: "Inicio"
    fr: "Domicile"
  Contact:
    en: "Contact"
    es: "Contacto"
    fr: "Contact"
  About:
    en: "About"
    es: "Nosotros"
    fr: "Nous"
  ContactUs:
    en: "Contact Us"
    es: "Contáctenos"
    fr: "Nous Contacter"
  AboutUs:
    en: "About Us"
    es: "Acerca de Nosotros"
    fr: "à propos de nous"
  LoremIpsum:
    en: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    es: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    fr: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  Copyright:
    en: "Copyright ©2021 All rights reserved"
    es: "Copyright ©2021 All rights reserved"
    fr: "Copyright ©2021 All rights reserved"
  PrivacyPolicy:
    en: "Privacy Policy"
    es: "Política de Privacidad"
    fr: "Lorem Ipsum"
  TermsOfService:
    en: "Terms of Service"
    es: "Términos y Condiciones"
    fr: "Lorem Ipsum"
  Description:
    en: "Lorem Ipsum"
    es: "Lorem Ipsum"
    fr: "Lorem Ipsum"
  Keywords:
    en: "Lorem Ipsum"
    es: "Lorem Ipsum"
    fr: "Lorem Ipsum"
  Lifestyle:
    en: "Lifestyle"
    es: "Estilo de Vida"
    fr: "Style de Vie"
  Music:
    en: "Music"
    es: "Música"
    fr: "Musique"
  Food:
    en: "Food"
    es: "Comida"
    fr: "Nourriture"
  Life:
    en: "The K Life"
    es: "The K Life"
    fr: "The K Life"
  Language:
    en: "Language"
    es: "Lenguaje"
    fr: "Lorem Ipsum"
  Coats:
    en: "Coats"
    es: "Sacos"
    fr: "Manteaux"
  Blazers:
    en: "Blazers"
    es: "Americanas"
    fr: "Blazers"
  Accessories:
    en: "Accessories"
    es: "Accesorios"
    fr: "Accessoires"
  All:
    en: "View All"
    es: "Ver Todo"
    fr: "Voir tout"
  JacketsPuffers:
    en: "Jackets / Puffers"
    es: "Chaquetas / Fumadoras"
    fr: "Veste / Puffers"
  Jackets:
    en: "Jackets"
    es: "Chaquetas"
    fr: "Vestes"
  Puffers:
    en: "Puffers"
    es: "Fumadoras"
    fr: "Puffers"
  Denim:
    en: "Denim"
    es: "Denim"
    fr: "Denim"
  DressesMono:
    en: "Dresses / Monos"
    es: "Vestidos / Monos"
    fr: "Robes / Combinaison"
  Maxi:
    en: "Maxi"
    es: "Maxi"
    fr: "Maxi"
  JumpSuits:
    en: "Jump Suits"
    es: "Mono"
    fr: "Combinaison"
  ShirtsTops:
    en: "Shirts / Tops"
    es: "Camisas / Tops"
    fr: "Chemise / Haunts"
  Shirts:
    en: "Shirts"
    es: "Camisas"
    fr: "Chemises"
  Blouses:
    en: "Blouses"
    es: "Blusas"
    fr: "Chemisières"
  Tops:
    en: "Tops"
    es: "Tops"
    fr: "Tops"
  CropTops:
    en: "Crop Tops"
    es: "Crop Tops"
    fr: "Hauts Courts"
  Tshirts:
    en: "T-Shirts"
    es: "Remeras"
    fr: "T-Shirts"
  Printed:
    en: "Printed"
    es: "Impreso"
    fr: "Imprimée"
  Cropped:
    en: "Cropped"
    es: "Recortado"
    fr: "Tondu"
  LongSleeve:
    en: "Long Sleeve"
    es: "Manga Larga"
    fr: "Manche Longue"
  TankTops:
    en: "Tank Tops"
    es: "Camiseta"
    fr: "Débardeurs"
  ShortSleeve:
    en: "Short Sleeve"
    es: "Manga Corta"
    fr: "Manche Courte"
  Knitwear:
    en: "Knitwear"
    es: "Tricot"
    fr: "Tricots"
  Cardigans:
    en: "Cargidans"
    es: "Cardigán"
    fr: "Cardigans"
  Sweatters:
    en: "Sweaters"
    es: "Suéteres"
    fr: "Chandails"
  KnitTops:
    en: "Knit Tops"
    es: "Tops"
    fr: "Tricots"
  Dresses:
    en: "Dresses"
    es: "Vestidos"
    fr: "Robes"
  TurtleNeck:
    en: "Turtle Neck"
    es: "Cuello de Tortuga"
    fr: "Col Roulé"
  Basics:
    en: "Basics"
    es: "Básicos"
    fr: "Basiques"
  Pantalones:
    en: "Pantalones"
    es: "Pantalones"
    fr: "Pantalones"
  Office:
    en: "Office"
    es: "Oficina"
    fr: "Bureau"
  Legging:
    en: "Leggings"
    es: "Polainas"
    fr: "Leggings"
  Joggers:
    en: "Joggers"
    es: "Corredores"
    fr: "Joggeurs"
  Jeans:
    en: "Jeans"
    es: "Jeans"
    fr: "Jeans"
  HighWaist:
    en: "High Waist"
    es: "Cintura Alta"
    fr: "Taille Haute"
  MidWaist:
    en: "Mid Waist"
    es: "Cintura Media"
    fr: "Taille Moyenne"
  Slouchy:
    en: "Slouchy"
    es: "Desgarbado"
    fr: "Mou"
  MomFit:
    en: "Mom Fit"
    es: "Mom Fit"
    fr: "Maman en Forme"
  Baggy:
    en: "Baggy"
    es: "Holgado"
    fr: "Bouffant"
  Straight:
    en: "Straight"
    es: "Ajustado"
    fr: "Droit"
  Slim:
    en: "Slim"
    es: "Delgado"
    fr: "Mince"
  SkirtsShorts:
    en: "Skirts / Shorts"
    es: "Faldas / Shorts"
    fr: "Jupes / Shorts"
  Mini:
    en: "Mini"
    es: "Mini"
    fr: "Mini"
  Midi:
    en: "Midi"
    es: "Midi"
    fr: "Mi-Longue"
  Pleated:
    en: "Pleated"
    es: "Plisado"
    fr: "Pliseé"
  Shorts:
    en: "Shorts"
    es: "Shorts"
    fr: "Shorts"
  TShirts:
    en: "T-Shirts"
    es: "Remeras"
    fr: "T-Shirts"
  SweatShirt:
    en: "Sweat-Shirt"
    es: "Sudaderas"
    fr: "Sweat-Shirt"
  Bags:
    en: "Bags"
    es: "Bolsos"
    fr: "Sacs"
  CrossBodyBags:
    en: "Cross Body Bags"
    es: "Bolsos Cruzados"
    fr: "SAC BANDOULIÈRES"
  MidiBags:
    en: "Midi Bags"
    es: "Mini Bolso"
    fr: "SAC À MAIN"
  LargeBags:
    en: "Large Bags"
    es: "Bolsa Grande"
    fr: "GRAND SAC / SAC À DOS"
  Jewerly:
    en: "Jewerly"
    es: "Joyería"
    fr: "Bijoux"
  Belts:
    en: "Belts"
    es: "Cinturones"
    fr: "Ceitures"
  Sunglasses:
    en: "Sunglasses"
    es: "Gafas de Sol"
    fr: ""
  HatsCaps:
    en: "Hats / Caps"
    es: "Sombreros / Gorras"
    fr: "Chapeaux"
  Handkerchiefs:
    en: "Handkerchiefs"
    es: "Bufandas"
    fr: "Mouchoir"
  Legal:
    en: "Legal"
    es: "Legal"
    fr: "Legal"
  FastFreeDelivery:
    en: "Fast & Free Delivery"
    es: "Envío Gratis y Rápido"
    fr: "Lorem Ipsum"
  Lorem:
    en: "Lorem Ipsum Dolor Sit Amet"
    es: "Lorem Ipsum Dolor Sit Amet"
    fr: "Lorem Ipsum Dolor Sit Amet"
  FirstCollection:
    en: "Collection Houses Our First-Ever"
    es: "Lorem Ipsum Dolor Sit Amet"
    fr: "Lorem Ipsum Dolor Sit Amet"
  SecondCollection:
    en: "Established fact that by the readable content"
    es: "Lorem Ipsum Dolor Sit Amet"
    fr: "Lorem Ipsum Dolor Sit Amet"
  ThirdCollection:
    en: "Established fact that by the readable content"
    es: "Lorem Ipsum Dolor Sit Amet"
    fr: "Lorem Ipsum Dolor Sit Amet"
  ViewMore:
    en: "View More"
    es: "Ver Mas"
    fr: "Lorem Ipsum"
  SearchPlaceholder:
    en: "What are you looking for?"
    es: "Qué estás buscando?"
    fr: "Lorem Ipsum"
  Search:
    en: "Search"
    es: "Buscar"
    fr: "Lorem Ipsum"
  Catalog:
    en: "Catalog"
    es: "Catálogo"
    fr: "Lorem Ipsum"
  CatalogError:
    en: "The catalog can't be rendered at this moment"
    es: "El catálogo no se puede mostrar en este momento"
    fr: "Lorem Ipsum Dolor Sit Amet"
  Loading:
    en: "Loading..."
    es: "Cargando..."
    fr: "Lorem Ipsum"
  View:
    en: "View"
    es: "Ver"
    fr: "Ipsum"

# --------------------------------------------
# Links Configuration 
# --------------------------------------------
Link:
  Instagram: "404.html"
  Facebook: "404.html"
  Twitter: "404.html"
  Pinterest: "404.html"
  Music: "404.html"
  Food: "404.html"
  Life: "404.html"

# --------------------------------------------
# Categories Configuration
# --------------------------------------------
Categories:
  Coats:
    Image: "categories/jackets.jpeg"
    Type: "COAT"
    Subcategories:
      JacketsPuffers:
        Filters:
          All:
            Type: "COAT"
          Jackets:
            Type: "JACKET"
          Puffers:
            Type: "PUFFER"
          Denim:
            Type: "DENIM"
  Blazers:
    Image: "categories/blazers.jpeg"
    Type: "BLAZERS"
    Subcategories:
      DressesMono:
        Type: "DRESS"
        Filters:
          All:
            Type: "DRESS"
          Mini:
            Type: "MIDI-DRESS"
          Midi:
            Type: "MIDI-DRESS"
          Maxi:
            Type: "MAXI-DRESS"
          JumpSuits:
            Type: "JUMP-SUIT"
      ShirtsTops:
        Type: "SHIRT"
        Filters:
          All:
            Type: "SHIRT"
          Shirts:
            Type: "SHIRT"
          Blouses:
            Type: "BLOUSE"
          Tops:
            Type: "TOP"
          CropTops:
            Type: "CROP-TOP"
      TShirts:
        Type: "TSHIRT"
        Filters:
          All:
            Type: "TSHIRT"
          Basics:
            Type: "BASIC-TSHIRT"
          Printed:
            Type: "PRINTED-TSHIRT"
          Cropped:
            Type: "CROPPED-TSHIRT"
          LongSleeve:
            Type: "LONG-SLEEVE-TSHIRT"
          TankTops:
            Type: "TANK-TOPS-TSHIRT"
          ShortSleeve:
            Type: "SHORT-SLEEVE-TSHIRT"
      Knitwear:
        Type: "KNITWEAR"
        Filters:
          All:
            Type: "KNITWEAR"
          Cardigans:
            Type: "CARDIGAN"
          Sweatters:
            Type: "SWEATTER"
          KnitTops:
            Type: "KNIT-TOP"
          Dresses:
            Type: "KNIT-DRESS"
          TurtleNeck:
            Type: "TURTLE-NECK"
          Basics:
            Type: "BASIC-DRESS"
      Pantalones:
        TYPE: "PANTALON"
        Filters:
          All:
            TYPE: "PANTALON"
          Office:
            Type: "OFFICE"
          Legging:
            Type: "LEGGING"
          Joggers:
            Type: "JOGGER"
      Jeans:
        Type: "JEAN"
        Filters:
          All:
            Type: "JEAN"
          HighWaist:
            Type: "HIGH-WAIST"
          MidWaist:
            Type: "MID-WAIST"
          Slouchy:
            Type: "SLOUCHY"
          MomFit:
            Type: "MOM-FIT"
          Baggy:
            Type: "BAGGY"
          Straight:
            Type: "STRAIGHT"
          Slim:
            Type: "SLIM"
      SkirtsShorts:
        Type: "SKIRTS-SHORT"
        Filters:
          All:
            Type: "SKIRTS-SHORT"
          Mini:
            Type: "MINI-SKIRT"
          Midi:
            Type: "MIDI-SKIRT"
          Pleated:
            Type: "PLEATED-SKIRT"
          Shorts:
            Type: "SHORT-SKIT"
      SweatShirt:
        Filter: "SWEAT-SHIRT"
        Filters:
          All:
            Type: "SWEAT-SHIRT"
  Accessories:
    Type: "ACCESSORY"
    Image: "categories/accessories.jpeg"
    Subcategories:
      Bags:
        Type: "BAG"
        Filters:
          All:
            Type: "BAG"
          CrossBodyBags:
            Type: "CROSS-BODY-BAG"
          MidiBags:
            Type: "MIDI-BAG"
          LargeBags:
            Type: "LARGE-BAG"
      Accessories:
        Type: "ACCESSORY"
        Filters:
          All:
            Type: "ACCESSORY"
          Jewerly:
            Type: "JEWERLY"
          Belts:
            Type: "BELT"
          Sunglasses:
            Type: "SUNGLASS"
          HatsCaps:
            Type: "HATS-CAP"
          Handkerchiefs:
            Type: "HANDKERCHIEF"

# --------------------------------------------
# Collections Configuration
# --------------------------------------------
Collections:
  Default: "217567887516"
  FirstCollection:
    Image: "collections/1.png"
    Filter: "collection-1"
  SecondCollection:
    Image: "collections/2.png"
    Filter: "collection-2"
  ThirdCollection:
    Image: "collections/3.png"
    Filter: "collection-3"
