# --------------------------------------------
# Marseille Configuration File
# --------------------------------------------

# --------------------------------------------
# Application Configuration
# --------------------------------------------
Application:
  Name: "The K Look"
  Email: "the.k.look2020@gmail.com"
  Version: "v1.0.0"

# --------------------------------------------
# Language Configuration
# --------------------------------------------
Language:
  English:
    Code: "en"
    Title: "English"
  Spanish:
    Code: "es"
    Title: "Spanish"
  French:
    Code: "fr"
    Title: "French"

# --------------------------------------------
# Build Configuration
# --------------------------------------------
Build:
  Templates: "src"
  Media: "media"
  Package: "build"

# --------------------------------------------
# Style Configuration
# --------------------------------------------
Style:
  White: "#F5F8FA"
  Silver: "#BDC3C7"
  Black: "#282828"
  LightGray: "#95A5A6"
  DarkGray: "#7f8C8D"
  Primary: "#3498DB"
  Secondary: "#2980B9"
  Tertiary: "#9B59B6"

# --------------------------------------------
# Assets Configuration
# --------------------------------------------
Assets:
  Logo: "brand/the k look v2.png"

# --------------------------------------------
# Strings Configuration
# --------------------------------------------
Strings:
  Home:
    en: "Home"
    es: "Inicio"
    fr: "Domicile"
  Contact:
    en: "Contact"
    es: "Contacto"
    fr: "Contact"
  About:
    en: "About"
    es: "Nosotros"
    fr: "Nous"
  ContactUs:
    en: "Contact Us"
    es: "Contáctenos"
    fr: "Nous Contacter"
  AboutUs:
    en: "About Us"
    es: "Acerca de Nosotros"
    fr: "à propos de nous"
  LoremIpsum:
    en: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    es: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    fr: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  Copyright:
    en: "Copyright ©2021 All rights reserved"
    es: "Copyright ©2021 All rights reserved"
    fr: "Copyright ©2021 All rights reserved"
  PrivacyPolicy:
    en: "Privacy Policy"
    es: "Política de Privacidad"
    fr: "TODO"
  TermsOfService:
    en: "Terms of Service"
    es: "Términos y Condiciones"
    fr: "TODO"
  Description:
    en: "TODO"
    es: "TODO"
    fr: "TODO"
  Keywords:
    en: "TODO"
    es: "TODO"
    fr: "TODO"
  Lifestyle:
    en: "Lifestyle"
    es: "Estilo de Vida"
    fr: "Style de Vie"
  Music:
    en: "Music"
    es: "Música"
    fr: "Musique"
  Food:
    en: "Food"
    es: "Comida"
    fr: "Nourriture"
  Life:
    en: "The K Life"
    es: "The K Life"
    fr: "The K Life"
  Language:
    en: "Language"
    es: "Lenguaje"
    fr: "TODO"
  Coats:
    en: "Coats"
    es: "Sacos"
    fr: "Manteaux"
  Blazers:
    en: "Blazers"
    es: "Americanas"
    fr: "Blazers"
  Accessories:
    en: "Accessories"
    es: "Accesorios"
    fr: "Accessoires"
  All:
    en: "View All"
    es: "Ver Todo"
    fr: "Voir tout"
  JacketsPuffers:
    en: "Jackets / Puffers"
    es: "Chaquetas / Fumadoras"
    fr: "Veste / Puffers"
  Jackets:
    en: "Jackets"
    es: "Chaquetas"
    fr: "Vestes"
  Puffers:
    en: "Puffers"
    es: "Fumadoras"
    fr: "Puffers"
  Denim:
    en: "Denim"
    es: "Denim"
    fr: "Denim"
  DressesMono:
    en: "Dresses / Monos"
    es: "Vestidos / Monos"
    fr: "Robes / Combinaison"
  Maxi:
    en: "Maxi"
    es: "Maxi"
    fr: "Maxi"
  JumpSuits:
    en: "Jump Suits"
    es: "Mono"
    fr: "Combinaison"
  ShirtsTops:
    en: "Shirts / Tops"
    es: "Camisas / Tops"
    fr: "Chemise / Haunts"
  Shirts:
    en: "Shirts"
    es: "Camisas"
    fr: "Chemises"
  Blouses:
    en: "Blouses"
    es: "Blusas"
    fr: "Chemisières"
  Tops:
    en: "Tops"
    es: "Tops"
    fr: "Tops"
  CropTops:
    en: "Crop Tops"
    es: "Crop Tops"
    fr: "Hauts Courts"
  Tshirts:
    en: "T-Shirts"
    es: "Remeras"
    fr: "T-Shirts"
  Printed:
    en: "Printed"
    es: "Impreso"
    fr: "Imprimée"
  Cropped:
    en: "Cropped"
    es: "Recortado"
    fr: "Tondu"
  LongSleeve:
    en: "Long Sleeve"
    es: "Manga Larga"
    fr: "Manche Longue"
  TankTops:
    en: "Tank Tops"
    es: "Camiseta"
    fr: "Débardeurs"
  ShortSleeve:
    en: "Short Sleeve"
    es: "Manga Corta"
    fr: "Manche Courte"
  Knitwear:
    en: "Knitwear"
    es: "Tricot"
    fr: "Tricots"
  Cardigans:
    en: "Cargidans"
    es: "Cardigán"
    fr: "Cardigans"
  Sweatters:
    en: "Sweaters"
    es: "Suéteres"
    fr: "Chandails"
  KnitTops:
    en: "Knit Tops"
    es: "Tops"
    fr: "Tricots"
  Dresses:
    en: "Dresses"
    es: "Vestidos"
    fr: "Robes"
  TurtleNeck:
    en: "Turtle Neck"
    es: "Cuello de Tortuga"
    fr: "Col Roulé"
  Basics:
    en: "Basics"
    es: "Básicos"
    fr: "Basiques"
  Pantalones:
    en: "Pantalones"
    es: "Pantalones"
    fr: "Pantalones"
  Office:
    en: "Office"
    es: "Oficina"
    fr: "Bureau"
  Legging:
    en: "Leggings"
    es: "Polainas"
    fr: "Leggings"
  Joggers:
    en: "Joggers"
    es: "Corredores"
    fr: "Joggeurs"
  Jeans:
    en: "Jeans"
    es: "Jeans"
    fr: "Jeans"
  HighWaist:
    en: "High Waist"
    es: "Cintura Alta"
    fr: "Taille Haute"
  MidWaist:
    en: "Mid Waist"
    es: "Cintura Media"
    fr: "Taille Moyenne"
  Slouchy:
    en: "Slouchy"
    es: "Desgarbado"
    fr: "Mou"
  MomFit:
    en: "Mom Fit"
    es: "Mom Fit"
    fr: "Maman en Forme"
  Baggy:
    en: "Baggy"
    es: "Holgado"
    fr: "Bouffant"
  Straight:
    en: "Straight"
    es: "Ajustado"
    fr: "Droit"
  Slim:
    en: "Slim"
    es: "Delgado"
    fr: "Mince"
  SkirtsShorts:
    en: "Skirts / Shorts"
    es: "Faldas / Shorts"
    fr: "Jupes / Shorts"
  Mini:
    en: "Mini"
    es: "Mini"
    fr: "Mini"
  Midi:
    en: "Midi"
    es: "Midi"
    fr: "Mi-Longue"
  Pleated:
    en: "Pleated"
    es: "Plisado"
    fr: "Pliseé"
  Shorts:
    en: "Shorts"
    es: "Shorts"
    fr: "Shorts"
  TShirts:
    en: "T-Shirts"
    es: "Remeras"
    fr: "T-Shirts"
  SweatShirt:
    en: "Sweat-Shirt"
    es: "Sudaderas"
    fr: "Sweat-Shirt"
  Bags:
    en: "Bags"
    es: "Bolsos"
    fr: "Sacs"
  CrossBodyBags:
    en: "Cross Body Bags"
    es: "Bolsos Cruzados"
    fr: "SAC BANDOULIÈRES"
  MidiBags:
    en: "Midi Bags"
    es: "Mini Bolso"
    fr: "SAC À MAIN"
  LargeBags:
    en: "Large Bags"
    es: "Bolsa Grande"
    fr: "GRAND SAC / SAC À DOS"
  Jewerly:
    en: "Jewerly"
    es: "Joyería"
    fr: "Bijoux"
  Belts:
    en: "Belts"
    es: "Cinturones"
    fr: "Ceitures"
  Sunglasses:
    en: "Sunglasses"
    es: "Gafas de Sol"
    fr: ""
  HatsCaps:
    en: "Hats / Caps"
    es: "Sombreros / Gorras"
    fr: "Chapeaux"
  Handkerchiefs:
    en: "Handkerchiefs"
    es: "Bufandas"
    fr: "Mouchoir"
  Legal:
    en: "Legal"
    es: "Legal"
    fr: "Legal"
  FastFreeDelivery:
    en: "Fast & Free Delivery"
    es: "Envío Gratis y Rápido"
    fr: "TODO"
  Lorem:
    en: "Lorem Ipsum Dolor Sit Amet"
    es: "Lorem Ipsum Dolor Sit Amet"
    fr: "Lorem Ipsum Dolor Sit Amet"

# --------------------------------------------
# Links Configuration 
# --------------------------------------------
Link:
  Instagram: "#"
  Facebook: "#"
  Twitter: "#"
  Pinterest: "#"
  Music: "#"
  Food: "#"
  Life: "#"

# --------------------------------------------
# Categories Configuration
# --------------------------------------------
Categories:
  Coats:
    Image: "categories/jackets.jpeg"
    Subcategories:
      JacketsPuffers:
        Filters:
          All:
            Filter: "all-jackets"
          Jackets:
            Filter: "jackets"
          Puffers:
            Filter: "puffers"
          Denim:
            Filter: "denim"
  Blazers:
    Image: "categories/blazers.jpeg"
    Subcategories:
      DressesMono:
        Filters:
          All:
            Filter: "all-dresses"
          Mini:
            Filter: "mini-dresses"
          Midi:
            Filter: "midi-dresses"
          Maxi:
            Filter: "maxi-dresses"
          JumpSuits:
            Filter: "jump-suites"
      ShirtsTops:
        Filters:
          All:
            Filter: "all-shirts"
          Shirts:
            Filter: "shirts"
          Blouses:
            Filter: "blouses"
          Tops:
            Filter: "tops"
          CropTops:
            Filter: "crop-tops"
      TShirts:
        Filters:
          All:
            Filter: "all-t-shirts"
          Basics:
            Filter: "basic-t-shirts"
          Printed:
            Filter: "printed-t-shirts"
          Cropped:
            Filter: "cropped-t-shirts"
          LongSleeve:
            Filter: "long-sleeve-t-shirts"
          TankTops:
            Filter: "tank-tops-t-shirts"
          ShortSleeve:
            Filter: "short-sleeve-t-shirts"
      Knitwear:
        Filters:
          All:
            Filter: "all-knitwear"
          Cardigans:
            Filter: "cardigans"
          Sweatters:
            Filter: "sweatters"
          KnitTops:
            Filter: "knit-tops"
          Dresses:
            Filter: "knit-dresses"
          TurtleNeck:
            Filter: "turtle-neck"
          Basics:
            Filter: "basic-dresses"
      Pantalones:
        Filters:
          All:
            Filter: "all-pantalones"
          Office:
            Filter: "office"
          Legging:
            Filter: "leggings"
          Joggers:
            Filter: "joggers"
      Jeans:
        Filters:
          All:
            Filter: "all-jeans"
          HighWaist:
            Filter: "high-waist"
          MidWaist:
            Filter: "mid-waist"
          Slouchy:
            Filter: "slouchy"
          MomFit:
            Filter: "mom-fit"
          Baggy:
            Filter: "baggy"
          Straight:
            Filter: "straight"
          Slim:
            Filter: "slim"
      SkirtsShorts:
        Filters:
          All:
            Filter: "all-skirts"
          Mini:
            Filter: "mini-skirts"
          Midi:
            Filter: "midi-skirts"
          Pleated:
            Filter: "pleated-skirts"
          Shorts:
            Filter: "short-skirts"
      SweatShirt:
        Filters:
          All:
            Filter: "all-sweat-shirts"
  Accessories:
    Image: "categories/accessories.jpeg"
    Subcategories:
      Bags:
        Filters:
          All:
            Filter: "all-bags"
          CrossBodyBags:
            Filter: "cross-body-bags"
          MidiBags:
            Filter: "midi-bags"
          LargeBags:
            Filter: "large-bags"
      Accessories:
        Filters:
          All:
            Filter: "all-accessories"
          Jewerly:
            Filter: "jewerly"
          Belts:
            Filter: "belts"
          Sunglasses:
            Filter: "sunglasses"
          HatsCaps:
            Filter: "hats-caps"
          Handkerchiefs:
            Filter: "handkerchiefs"
