# --------------------------------------------
# Kain Configuration File
# --------------------------------------------

# --------------------------------------------
# Application Configuration
# --------------------------------------------
Application:
  Name: "The K Look"
  Email: "the.k.look2020@gmail.com"
  Version: "v1.0.0"

# --------------------------------------------
# Language Configuration
# --------------------------------------------
Language:
  English:
    Code: "en"
    Title: "English"
  Spanish:
    Code: "es"
    Title: "Spanish"
  French:
    Code: "fr"
    Title: "French"

# --------------------------------------------
# Build Configuration
# --------------------------------------------
Build:
  Templates: "src"
  Media: "media"
  Package: "build"

# --------------------------------------------
# Style Configuration
# --------------------------------------------
Style:
  White: "#F5F8FA"
  Silver: "#BDC3C7"
  Black: "#282828"
  LightGray: "#95A5A6"
  DarkGray: "#7f8C8D"
  Primary: "#3498DB"
  Secondary: "#2980B9"

# --------------------------------------------
# Assets Configuration
# --------------------------------------------
Assets:
  Logo: "k/the k look v2.png"

# --------------------------------------------
# Strings Configuration
# --------------------------------------------
Strings:
  Home:
    en: "Home"
    es: "Inicio"
    fr: "TODO"
  Contact:
    en: "Contact"
    es: "Contacto"
    fr: "TODO"
  About:
    en: "About"
    es: "Nosotros"
    fr: "TODO"
  ContactUs:
    en: "Contact Us"
    es: "Contáctenos"
    fr: "TODO"
  AboutUs:
    en: "About Us"
    es: "Acerca de Nosotros"
    fr: "TODO"
  LoremIpsum:
    en: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    es: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    fr: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  Copyright:
    en: "Copyright ©2021 All rights reserved"
    es: "Copyright ©2021 All rights reserved"
    fr: "TODO"
  PrivacyPolicy:
    en: "Privacy Policy"
    es: "Política de Privacidad"
    fr: "TODO"
  TermsOfService:
    en: "Terms of Service"
    es: "Términos y Condiciones"
    fr: "TODO"
  Description:
    en: "TODO"
    es: "TODO"
    fr: "TODO"
  Keywords:
    en: "TODO"
    es: "TODO"
    fr: "TODO"
  Lifestyle:
    en: "Lifestyle"
    es: "Estilo de Vida"
    fr: "Style de Vie"
  Music:
    en: "Music"
    es: "Musica"
    fr: "Musique"
  Food:
    en: "Food"
    es: "Comida"
    fr: "Nourriture"
  Life:
    en: "The K Life"
    es: "The K Life"
    fr: "The K Life"
  Coats:
    en: "Coats"
    es: ""
    fr: ""
  Jackets:
    en: "Jacket / Puffers"
    es: "Chaquetas"
    fr: ""
  Blazers:
    en: "Blazers"
    es: ""
    fr: ""
  Dresses:
    en: "Dresses / Mono"
    es: ""
    fr: ""
  Shirts:
    en: "Shirt / Tops"
    es: ""
    fr: ""
  Tshirts:
    en: "T-Shirts"
    es: ""
    fr: ""
  Knitwear:
    en: "Knitwear"
    es: ""
    fr: ""
  Pantalones:
    en: "Pantalones"
    es: ""
    fr: ""
  Jeans:
    en: "Jeans"
    es: ""
    fr: ""
  Skirts:
    en: "Skirts / Shorts"
    es: ""
    fr: ""
  SweatShirt:
    en: "Sweat-Shirts"
    es: ""
    fr: ""
  Bags:
    en: "Bags"
    es: ""
    fr: ""
  Accessories:
    en: "Accessories"
    es: ""
    fr: ""
  Language:
    en: "Language"
    es: "Lenguaje"
    fr: "TODO"
  Other:
    en: "Other"
    es: "Otros"
    fr: "TODO"

# --------------------------------------------
# Links Configuration 
# --------------------------------------------
Link:
  Instagram: "#"
  Facebook: "#"
  Twitter: "#"
  Pinterest: "#"
  Music: "#"
  Food: "#"
  Life: "#"

# --------------------------------------------
# Categories Configuration
# --------------------------------------------
Categories:
  Coats:
    Subcategories:
      Jackets:
        Filters:
          All:
            filter: ""
          Jackets:
            filter: "jackets"
          Puffers:
            filter: "puffers"
          Denim:
            filter: "denim"
  Blazers:
    Subcategories:
      Dresses:
        Filters:
          All:
            filter: ""
          Mini:
            filter: ""
          Midi:
            filter: ""
          Maxi:
            filter: ""
          JumpSuits:
            filter: ""
      Shirts:
        Filters:
          All:
            filter: ""
          Shirts:
            filter: ""
          Blouses:
            filter: ""
          Tops:
            filter: ""
          Croctops:
            filter: ""
      Tshirts:
        Filters:
          All:
            filter: ""
          Basic:
            filter: ""
          Printed:
            filter: ""
          Cropped:
            filter: ""
          LongSleeve:
            filter: ""
          TankTops:
            filter: ""
          ShortSleeve:
            filte: ""
      Knitwear:
        Filters:
          All:
            filter: ""
          Cardigans:
            filter: ""
          Sweatters:
            filter: ""
          KnitTops:
            filter: ""
          Dresses:
            filter: ""
          TurtleNeck:
            filter: ""
          Basics:
            filter: ""
      Pantalones:
        Filters:
          All:
            filter: ""
          Office:
            filter: ""
          Legging:
            filter: ""
          Joggers:
            filter: ""
      Jeans:
        Filters:
          All:
            filter: ""
          HighWaist:
            filter: ""
          MidWaist:
            filter: ""
          Slouchy:
            filter: ""
          MomFit:
            filter: ""
          Baggy:
            filter: ""
          Straight:
            filter: ""
          Slim:
            filter: ""
      Skirts:
        Filters:
          All:
            filter: ""
          Mini:
            filter: ""
          Midi:
            filter: ""
          Pleated:
            filter: ""
          Shorts:
            filter: ""
      SweatShirt:
        Filters:
          All:
            filter: ""
  Other:
    Subcategories:
      Bags:
        Filters:
          All:
            filter: ""
          CrossBodyBags:
            filter: ""
          MidiBags:
            filter: ""
          LargeBags:
            filter: ""
      Accessories:
        Filters:
          All:
            filter: ""
          Jewerly:
            filter: ""
          Belts:
            filter: ""
          Sunglasses:
            filter: ""
